# Generated by Django 4.1 on 2025-10-04 10:35

import django.db.models.deletion
import django.utils.timezone

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="pin_code",
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.CreateModel(
            name="ClockRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "clock_type",
                    models.CharField(
                        choices=[("in", "Clock In"), ("out", "Clock Out")], max_length=3
                    ),
                ),
                ("location_lat", models.FloatField()),
                ("location_lng", models.FloatField()),
                ("photo", models.ImageField(upload_to="clock_photos/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clock_records",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "clock_type", "timestamp")},
            },
        ),
    ]
