# Generated by Django 4.1 on 2025-10-08 19:55

import datetime

import django.db.models.deletion
import django.utils.timezone

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employee_pin_code_clockrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="employeescore",
            index=models.Index(fields=["employee", "date"], name="employees_e_employe_6b0b4f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="employeescore",
            unique_together={("employee", "date")},
        ),
    ]
